apiVersion: v1
kind: Service
metadata:
  name: fintrust-transaction-api-service
spec:
  type: LoadBalancer
  selector:
    app: fintrust-transaction-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000